In [209]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import scipy.stats as st
from scipy.stats import linregress

In [211]:
# Student data filepath
student_data_path = "data/studentPerformanceFactors_Cleaned.csv"

# Student data dataframe created by reading the CSV with pandas
student_df = pd.read_csv(student_data_path)

#prints number of students
print(f"This data set has {len(student_df)} rows of student data")

This data set has 6377 rows of student data

In [213]:
encoded_df = student_df.copy()
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

#Different mapping method for machine learning model
encoded_df['Parental_Involvement'] = le.fit_transform(student_df['Parental_Involvement'])
encoded_df['Access_to_Resources'] = le.fit_transform(student_df['Access_to_Resources'])
encoded_df['Extracurricular_Activities'] = le.fit_transform(student_df['Extracurricular_Activities'])
encoded_df['Motivation_Level'] = le.fit_transform(student_df['Motivation_Level'])
encoded_df['Internet_Access'] = le.fit_transform(student_df['Internet_Access'])
encoded_df['Family_Income'] = le.fit_transform(student_df['Family_Income'])
encoded_df['Teacher_Quality'] = le.fit_transform(student_df['Teacher_Quality'])
encoded_df['School_Type'] = le.fit_transform(student_df['School_Type'])
encoded_df['Peer_Influence'] = le.fit_transform(student_df['Peer_Influence'])
encoded_df['Learning_Disabilities'] = le.fit_transform(student_df['Learning_Disabilities'])
encoded_df['Parental_Education_Level'] = le.fit_transform(student_df['Parental_Education_Level'])
encoded_df['Distance_from_Home'] = le.fit_transform(student_df['Distance_from_Home'])
encoded_df['Gender'] = le.fit_transform(student_df['Gender'])
encoded_df.head(25)

,Hours_Studied,Attendance,Parental_Involvement,Access_to_Resources,Extracurricular_Activities,Sleep_Hours,Previous_Scores,Motivation_Level,Internet_Access,Tutoring_Sessions,...,Teacher_Quality,School_Type,Peer_Influence,Physical_Activity,Learning_Disabilities,Parental_Education_Level,Distance_from_Home,Gender,Exam_Score,Score_Difference
0,23,84,1,0,0,7,73,1,1,0,...,2,1,2,3,0,1,2,1,67,-6
1,19,64,1,2,0,8,59,1,1,2,...,2,1,0,4,0,0,1,0,61,2
2,24,98,2,2,1,7,91,2,1,2,...,2,1,1,4,0,2,2,1,74,-17
3,29,89,1,2,1,8,98,2,1,1,...,2,1,0,4,0,1,1,1,71,-27
4,19,92,2,2,1,6,65,2,1,3,...,0,1,1,4,0,0,2,0,70,5
5,19,88,2,2,1,8,89,2,1,3,...,2,1,2,3,0,2,2,1,71,-18
6,29,84,2,1,1,7,68,1,1,1,...,2,0,1,2,0,1,1,1,67,-1
7,25,78,1,0,1,6,50,2,1,1,...,0,1,0,2,0,1,0,1,66,16
8,17,94,2,0,0,6,80,0,1,0,...,1,0,1,1,0,0,2,1,69,-11
9,23,98,2,2,1,8,71,2,1,0,...,0,1,2,5,0,1,1,1,72,1
10,17,80,1,0,0,8,88,2,0,4,...,0,0,1,4,0,0,1,1,68,-20
11,17,97,2,0,1,6,87,1,1,2,...,0,0,1,2,0,1,2,1,71,-16
12,21,83,2,2,1,8,97,1,1,2,...,2,1,2,4,0,1,2,1,70,-27
13,9,82,2,2,1,8,72,2,1,2,...,2,0,2,3,0,2,2,1,66,-6
14,10,78,2,0,1,8,74,2,1,1,...,2,0,1,4,0,2,2,1,65,-9
15,17,68,2,2,0,8,70,2,1,2,...,2,0,2,4,0,1,2,0,64,-6
16,14,60,2,1,1,10,65,1,1,0,...,2,0,2,3,0,0,2,1,60,-5
17,22,70,1,2,1,6,82,2,1,1,...,0,1,1,3,0,1,2,0,65,-17
18,15,80,2,2,1,9,91,1,1,3,...,2,1,2,2,0,0,1,0,67,-24
19,12,75,2,0,1,7,58,2,1,3,...,2,0,2,4,0,0,2,1,66,8
20,29,78,2,2,0,5,99,0,1,0,...,2,1,0,1,0,1,1,0,69,-30
21,19,99,2,0,0,6,84,2,1,1,...,0,1,1,3,0,1,2,1,72,-12
22,20,74,2,0,0,8,89,1,1,1,...,2,1,0,2,0,0,1,0,66,-23
23,11,78,0,2,1,8,100,0,1,1,...,2,1,1,3,0,1,1,1,66,-34
24,17,65,1,0,1,5,75,2,1,2,...,2,1,2,3,0,1,2,0,63,-12

In [215]:
#Dataframe sorted by Exam scores and creates dataframe filter by exam scores over 90
A_grade_dataframe = student_df[(student_df["Exam_Score"] >= 90)].sort_values(["Exam_Score"], ascending=False)
A_grade_dataframe.head(10)

A_grade_dataframe = student_df[(student_df["Exam_Score"] >= 90)].sort_values(["Exam_Score"], ascending=False)
A_grade_dataframe.head(10)

,Hours_Studied,Attendance,Parental_Involvement,Access_to_Resources,Extracurricular_Activities,Sleep_Hours,Previous_Scores,Motivation_Level,Internet_Access,Tutoring_Sessions,...,Teacher_Quality,School_Type,Peer_Influence,Physical_Activity,Learning_Disabilities,Parental_Education_Level,Distance_from_Home,Gender,Exam_Score,Score_Difference
93,18,89,High,Medium,Yes,4,73,Medium,Yes,3,...,Medium,Private,Positive,2,No,College,Near,Female,100,27
2340,23,83,High,High,Yes,4,89,Low,Yes,1,...,Medium,Public,Negative,3,No,High School,Far,Male,99,10
3454,14,90,High,High,Yes,8,86,Medium,Yes,4,...,Medium,Private,Negative,2,No,High School,Near,Female,99,13
4051,28,90,Low,Medium,Yes,9,91,Medium,Yes,0,...,Medium,Public,Positive,2,No,College,Moderate,Female,98,7
6176,16,83,Low,Medium,Yes,8,92,Low,Yes,2,...,High,Public,Positive,4,No,Postgraduate,Near,Female,98,6
6130,28,96,High,Low,Yes,4,98,High,Yes,1,...,High,Public,Positive,3,No,High School,Near,Male,98,0
5763,25,99,Medium,Medium,Yes,7,77,Medium,Yes,0,...,High,Public,Neutral,3,No,High School,Near,Male,97,20
885,21,74,High,Medium,No,6,94,Medium,Yes,1,...,High,Public,Positive,1,No,High School,Near,Male,97,3
515,15,83,Medium,Medium,No,7,97,Medium,Yes,2,...,High,Private,Neutral,2,No,High School,Near,Female,97,0
3336,18,93,Medium,Medium,No,7,76,Low,Yes,2,...,Medium,Private,Neutral,4,No,High School,Near,Female,96,20

In [217]:
#Corr Coeff of all students
print(f"Hours_Studied {encoded_df["Exam_Score"].corr(encoded_df["Hours_Studied"])}")
print(f"Attendance {encoded_df["Exam_Score"].corr(encoded_df["Attendance"])}")
print(f"Parental_Involvement {encoded_df["Exam_Score"].corr(encoded_df["Parental_Involvement"])}")
print(f"Access_to_Resources {encoded_df["Exam_Score"].corr(encoded_df["Access_to_Resources"])}")
print(f"Extracurricular_Activities {encoded_df["Exam_Score"].corr(encoded_df["Extracurricular_Activities"])}")
print(f"Motivation_Level {encoded_df["Exam_Score"].corr(encoded_df["Motivation_Level"])}")
print(f"Internet_Access {encoded_df["Exam_Score"].corr(encoded_df["Internet_Access"])}")
print(f"Tutoring_Sessions {encoded_df["Exam_Score"].corr(encoded_df["Tutoring_Sessions"])}")
print(f"Family_Income {encoded_df["Exam_Score"].corr(encoded_df["Family_Income"])}")
print(f"Teacher_Quality {encoded_df["Exam_Score"].corr(encoded_df["Teacher_Quality"])}")
print(f"School_Type {encoded_df["Exam_Score"].corr(encoded_df["School_Type"])}")
print(f"Peer_Influence {encoded_df["Exam_Score"].corr(encoded_df["Peer_Influence"])}")
print(f"Physical_Activity {encoded_df["Exam_Score"].corr(encoded_df["Physical_Activity"])}")
print(f"Learning_Disabilities {encoded_df["Exam_Score"].corr(encoded_df["Learning_Disabilities"])}")
print(f"Parental_Education_Level {encoded_df["Exam_Score"].corr(encoded_df["Parental_Education_Level"])}")
print(f"Distance_from_Home {encoded_df["Exam_Score"].corr(encoded_df["Distance_from_Home"])}")
print(f"Gender {encoded_df["Exam_Score"].corr(encoded_df["Gender"])}")


encoded_df.head()

Hours_Studied 0.4461739730978629
Attendance 0.5816643103422525
Parental_Involvement -0.09424269222123187
Access_to_Resources -0.0902583068211735
Extracurricular_Activities 0.06231907859262715
Motivation_Level -0.017328395024338732
Internet_Access 0.05621883568721425
Tutoring_Sessions 0.15398584369680882
Family_Income -0.02057285402121521
Teacher_Quality -0.05763639771536052
School_Type -0.011833005389052022
Peer_Influence 0.0982712648509809
Physical_Activity 0.02525955393307201
Learning_Disabilities -0.08394051270810966
Parental_Education_Level 0.040856113344310364
Distance_from_Home 0.0896112479635467
Gender -0.0033693307738402005

,Hours_Studied,Attendance,Parental_Involvement,Access_to_Resources,Extracurricular_Activities,Sleep_Hours,Previous_Scores,Motivation_Level,Internet_Access,Tutoring_Sessions,...,Teacher_Quality,School_Type,Peer_Influence,Physical_Activity,Learning_Disabilities,Parental_Education_Level,Distance_from_Home,Gender,Exam_Score,Score_Difference
0,23,84,1,0,0,7,73,1,1,0,...,2,1,2,3,0,1,2,1,67,-6
1,19,64,1,2,0,8,59,1,1,2,...,2,1,0,4,0,0,1,0,61,2
2,24,98,2,2,1,7,91,2,1,2,...,2,1,1,4,0,2,2,1,74,-17
3,29,89,1,2,1,8,98,2,1,1,...,2,1,0,4,0,1,1,1,71,-27
4,19,92,2,2,1,6,65,2,1,3,...,0,1,1,4,0,0,2,0,70,5

In [219]:
#Corr Coeff of grade A students
A_grade_ec_dataframe = encoded_df[(encoded_df["Exam_Score"] >= 90)]

print(f"Hours_Studied {A_grade_ec_dataframe["Exam_Score"].corr(A_grade_ec_dataframe["Hours_Studied"])}")
print(f"Attendance {A_grade_ec_dataframe["Exam_Score"].corr(A_grade_ec_dataframe["Attendance"])}")
print(f"Parental_Involvement {A_grade_ec_dataframe["Exam_Score"].corr(A_grade_ec_dataframe["Parental_Involvement"])}")
print(f"Access_to_Resources {A_grade_ec_dataframe["Exam_Score"].corr(A_grade_ec_dataframe["Access_to_Resources"])}")
print(f"Extracurricular_Activities {A_grade_ec_dataframe["Exam_Score"].corr(A_grade_ec_dataframe["Extracurricular_Activities"])}")
print(f"Motivation_Level {A_grade_ec_dataframe["Exam_Score"].corr(A_grade_ec_dataframe["Motivation_Level"])}")
print(f"Internet_Access {A_grade_ec_dataframe["Exam_Score"].corr(A_grade_ec_dataframe["Internet_Access"])}")
print(f"Tutoring_Sessions {A_grade_ec_dataframe["Exam_Score"].corr(A_grade_ec_dataframe["Tutoring_Sessions"])}")
print(f"Family_Income {A_grade_ec_dataframe["Exam_Score"].corr(A_grade_ec_dataframe["Family_Income"])}")
print(f"Teacher_Quality {A_grade_ec_dataframe["Exam_Score"].corr(A_grade_ec_dataframe["Teacher_Quality"])}")
print(f"School_Type {A_grade_ec_dataframe["Exam_Score"].corr(A_grade_ec_dataframe["School_Type"])}")
print(f"Peer_Influence {A_grade_ec_dataframe["Exam_Score"].corr(A_grade_ec_dataframe["Peer_Influence"])}")
print(f"Physical_Activity {A_grade_ec_dataframe["Exam_Score"].corr(A_grade_ec_dataframe["Physical_Activity"])}")
print(f"Learning_Disabilities {A_grade_ec_dataframe["Exam_Score"].corr(A_grade_ec_dataframe["Learning_Disabilities"])}")
print(f"Parental_Education_Level {A_grade_ec_dataframe["Exam_Score"].corr(A_grade_ec_dataframe["Parental_Education_Level"])}")
print(f"Distance_from_Home {A_grade_ec_dataframe["Exam_Score"].corr(A_grade_ec_dataframe["Distance_from_Home"])}")
print(f"Gender {A_grade_ec_dataframe["Exam_Score"].corr(A_grade_ec_dataframe["Gender"])}")

A_grade_ec_dataframe.head(20)

Hours_Studied -0.05334088562137783
Attendance 0.4168816680587054
Parental_Involvement -0.3852806535982991
Access_to_Resources 0.23168735836324764
Extracurricular_Activities 0.3908859995240631
Motivation_Level 0.12405391296394767
Internet_Access 0.3837646205381243
Tutoring_Sessions 0.13744555685917534
Family_Income -0.09986465201419123
Teacher_Quality -0.17224081394230775
School_Type -0.24151097348212383
Peer_Influence 0.27205393213333634
Physical_Activity -0.34990957264470374
Learning_Disabilities nan
Parental_Education_Level 0.06509759789197254
Distance_from_Home 0.20976987209837775
Gender -0.2150910700181971

/opt/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2897: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
/opt/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2898: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]

,Hours_Studied,Attendance,Parental_Involvement,Access_to_Resources,Extracurricular_Activities,Sleep_Hours,Previous_Scores,Motivation_Level,Internet_Access,Tutoring_Sessions,...,Teacher_Quality,School_Type,Peer_Influence,Physical_Activity,Learning_Disabilities,Parental_Education_Level,Distance_from_Home,Gender,Exam_Score,Score_Difference
93,18,89,0,2,1,4,73,2,1,3,...,2,0,2,2,0,0,2,0,100,27
515,15,83,2,2,0,7,97,2,1,2,...,0,0,1,2,0,1,2,0,97,0
742,24,96,1,0,0,6,93,2,1,2,...,2,1,1,2,0,1,1,0,94,1
805,29,76,2,2,0,8,96,1,1,2,...,2,1,2,2,0,2,1,1,94,-2
885,21,74,0,2,0,6,94,2,1,1,...,0,1,2,1,0,1,2,1,97,3
1065,31,69,2,2,0,7,52,2,0,2,...,1,1,1,5,0,0,0,1,92,40
2212,21,70,0,0,0,9,66,2,1,1,...,1,1,1,4,0,0,1,1,91,25
2340,23,83,0,0,1,4,89,1,1,1,...,2,1,0,3,0,1,0,1,99,10
3017,19,90,2,0,1,5,90,1,1,0,...,2,1,1,2,0,0,0,0,94,4
3336,18,93,2,2,0,7,76,1,1,2,...,2,0,1,4,0,1,2,0,96,20
3454,14,90,0,0,1,8,86,2,1,4,...,2,0,0,2,0,1,2,0,99,13
4051,28,90,1,2,1,9,91,2,1,0,...,2,1,2,2,0,0,1,0,98,7
4153,21,67,2,2,1,6,88,2,1,1,...,2,0,2,5,0,2,2,0,95,7
4259,25,98,2,2,1,7,90,0,1,1,...,1,1,1,4,0,2,2,1,94,4
4383,26,69,0,0,0,7,95,1,0,0,...,2,1,0,3,0,2,2,0,93,-2
4433,25,73,2,2,1,7,56,2,1,2,...,2,1,1,4,0,1,2,0,93,37
4622,1,88,2,0,1,4,72,0,1,3,...,2,0,0,2,0,0,2,1,92,20
5763,25,99,2,2,1,7,77,2,1,0,...,0,1,1,3,0,1,2,1,97,20
6130,28,96,0,1,1,4,98,0,1,1,...,0,1,2,3,0,1,2,1,98,0
6176,16,83,1,2,1,8,92,1,1,2,...,0,1,2,4,0,2,2,0,98,6

In [183]:
#linear regression plot function
def linearRegressionplots(x_values, y_values, x_label="X-axis", y_label="Y-axis", title="Scatter Plot"):

    slope = linregress(x_values, y_values)
    (slope, intercept, rvalue, pvalue, stderr) = linregress(x_values, y_values)
    regress_values = x_values * slope + intercept
    line_eq = "y = " + str(round(slope,2)) + "x + " + str(round(intercept,2))

    
    print(f'The r-value is {rvalue}')
    plt.scatter(x_values, y_values)
    plt.plot(x_values, regress_values, "-r")
    plt.annotate(line_eq,(0,-20),fontsize=15,color="red")
    plt.xlabel(x_label)
    plt.ylabel(y_label)
    plt.title(title)

    return plt

In [185]:
#What patterns can be identified between specific ranges of study time, parent involvement, or other demographics? Isaiah
#Scatter plots
#Cluster Analysis
#Identify student groups: Group students based on similar characteristics (e.g., study habits, parental involvement, and academic performance).
#Analyze group differences: Compare the performance of different student groups.

#Does the ratio of male and female translate to those that have an A grade, or is one gender more successful than the other, despite the ratio? Isaiah
#

#Is there a correlation between the number of hours of sleep per night and attendance? Charles

#How does parental involvement affect the general motivation level of the students? Maryann



#Final Question Breakdown
#Q1: What patterns/relationships can be identified between specific factors and Exam_score/Difference for the top ? of students?
#Study time by exam score
#Box Plot

#Q2: Which factors out of the students control correlate to their score (Parental Involvement, Access to Resources, Internet Access, 
# Family_Income, Teacher_Quality, Learning Disability, Parent edu, ,Distance From Home, Gender)which of the factors or combo is best? ANOVA?
#?
#Socioecinomic status and performance group comparison
#scatter all students
#scatter students in the 90 and greater grade range
#?
#Learning disablity based grade performance comparison
#pie all students
#pie students diff grader than 90? or change their grade to an A

#Q3: Is there a correlation between the number of hours of sleep per night and attendance? Charles


#Q4: How does parental involvement affect the general motivation level of the students? Maryann
#?
#parental involvment based performance comparison
#scatter all students
#scatter students in the 90 and greater grade range

#?
#studying based grade diff comparison
#scatter all students
#scatter students diff grader than 90? or change their grade to an A

#?
#motivation based grade diff comparison
#scatter all students
#scatter students diff grader than 90? or change their grade to an A

#Q5: Based on this dataset, what factors optimize attendance(GreatScoreDifference)? and scores? All
#?
#tutoring based grade diff comparison
#scatter all students
#scatter students diff grader than 90? or change their grade to an A

In [ ]:
#Q1: 
#A1: 
#V1:
#v2:

In [187]:
#Q2: 
#A2: 
#V1:
#v2:

In [189]:
#Q3: 
#A3: 
#V1:
#v2:

In [191]:
#Q4: 
#A4: 
#V1:
#v2:

In [ ]:
#Q1:

plt.savefig("output_data/Fig1.png")

# Show plot
plt.show()


plt.savefig("output_data/Fig2.png")

# Show plot
plt.show()

In [196]:
#Q2: Does the ratio of male and female translate to those that have an A grade, or is one gender more successful than the other, despite the ratio? Isaiah
#Gender Based performance group comparison
#Bar chart of gender avgerage
#bar chart of gender representaion in the 90 and greater grade range

plt.savefig("output_data/Fig3.png")

# Show plot
plt.show()


plt.savefig("output_data/Fig4.png")

# Show plot
plt.show()

FileNotFoundError: [Errno 2] No such file or directory: '/Users/zay/Desktop/Boot Camp/Project1-SMU/output_data/Fig3.png'

In [199]:
#Charles Q3: Is there a correlation between the number of hours of sleep per night and attendance? Charles
#linearRegressionplots(A_grade_dataframe["Exam_Score"], A_grade_dataframe["Attendance"], "Exam Score", "Parental Attendance", "Exam Score by Attendance")
#dataframe sorted by Attendance
#Sorted_dataframe = student_df.sort_values(["Attendance"], ascending=False)
#Sorted_dataframe.head(15)
# Show plot
plt.savefig("output_data/Fig5.png")


# Show plot
plt.show()


plt.savefig("output_data/Fig6.png")

# Show plot
plt.show()

FileNotFoundError: [Errno 2] No such file or directory: '/Users/zay/Desktop/Boot Camp/Project1-SMU/output_data/Fig5.png'

In [ ]:
#Maryann Q4: How does parental involvement affect the general motivation level of the students? Maryann
#
plt.savefig("output_data/Fig7.png")


# Show plot
plt.show()


plt.savefig("output_data/Fig8.png")


# Show plot
plt.show()

,Hours_Studied,Attendance,Parental_Involvement,Access_to_Resources,Extracurricular_Activities,Sleep_Hours,Previous_Scores,Motivation_Level,Internet_Access,Tutoring_Sessions,...,Teacher_Quality,School_Type,Peer_Influence,Physical_Activity,Learning_Disabilities,Parental_Education_Level,Distance_from_Home,Gender,Exam_Score,Score_Difference
0,23,84,1,0,0,7,73,1,1,0,...,2,1,2,3,0,1,2,1,67,-6
1,19,64,1,2,0,8,59,1,1,2,...,2,1,0,4,0,0,1,0,61,2
2,24,98,2,2,1,7,91,2,1,2,...,2,1,1,4,0,2,2,1,74,-17
3,29,89,1,2,1,8,98,2,1,1,...,2,1,0,4,0,1,1,1,71,-27
4,19,92,2,2,1,6,65,2,1,3,...,0,1,1,4,0,0,2,0,70,5
5,19,88,2,2,1,8,89,2,1,3,...,2,1,2,3,0,2,2,1,71,-18
6,29,84,2,1,1,7,68,1,1,1,...,2,0,1,2,0,1,1,1,67,-1
7,25,78,1,0,1,6,50,2,1,1,...,0,1,0,2,0,1,0,1,66,16
8,17,94,2,0,0,6,80,0,1,0,...,1,0,1,1,0,0,2,1,69,-11
9,23,98,2,2,1,8,71,2,1,0,...,0,1,2,5,0,1,1,1,72,1
10,17,80,1,0,0,8,88,2,0,4,...,0,0,1,4,0,0,1,1,68,-20
11,17,97,2,0,1,6,87,1,1,2,...,0,0,1,2,0,1,2,1,71,-16
12,21,83,2,2,1,8,97,1,1,2,...,2,1,2,4,0,1,2,1,70,-27
13,9,82,2,2,1,8,72,2,1,2,...,2,0,2,3,0,2,2,1,66,-6
14,10,78,2,0,1,8,74,2,1,1,...,2,0,1,4,0,2,2,1,65,-9
15,17,68,2,2,0,8,70,2,1,2,...,2,0,2,4,0,1,2,0,64,-6
16,14,60,2,1,1,10,65,1,1,0,...,2,0,2,3,0,0,2,1,60,-5
17,22,70,1,2,1,6,82,2,1,1,...,0,1,1,3,0,1,2,0,65,-17
18,15,80,2,2,1,9,91,1,1,3,...,2,1,2,2,0,0,1,0,67,-24
19,12,75,2,0,1,7,58,2,1,3,...,2,0,2,4,0,0,2,1,66,8
20,29,78,2,2,0,5,99,0,1,0,...,2,1,0,1,0,1,1,0,69,-30
21,19,99,2,0,0,6,84,2,1,1,...,0,1,1,3,0,1,2,1,72,-12
22,20,74,2,0,0,8,89,1,1,1,...,2,1,0,2,0,0,1,0,66,-23
23,11,78,0,2,1,8,100,0,1,1,...,2,1,1,3,0,1,1,1,66,-34
24,17,65,1,0,1,5,75,2,1,2,...,2,1,2,3,0,1,2,0,63,-12

Hours_Studied 0.4461739730978629
Attendance 0.5816643103422525
Parental_Involvement -0.09424269222123187
Access_to_Resources -0.0902583068211735
Extracurricular_Activities 0.06231907859262715
Motivation_Level -0.017328395024338732
Internet_Access 0.05621883568721425
Tutoring_Sessions 0.15398584369680882
Family_Income -0.02057285402121521
Teacher_Quality -0.05763639771536052
School_Type -0.011833005389052022
Peer_Influence 0.0982712648509809
Physical_Activity 0.02525955393307201
Learning_Disabilities -0.08394051270810966
Parental_Education_Level 0.040856113344310364
Distance_from_Home 0.0896112479635467
Gender -0.0033693307738402005

,Hours_Studied,Attendance,Parental_Involvement,Access_to_Resources,Extracurricular_Activities,Sleep_Hours,Previous_Scores,Motivation_Level,Internet_Access,Tutoring_Sessions,...,Teacher_Quality,School_Type,Peer_Influence,Physical_Activity,Learning_Disabilities,Parental_Education_Level,Distance_from_Home,Gender,Exam_Score,Score_Difference
0,23,84,1,0,0,7,73,1,1,0,...,2,1,2,3,0,1,2,1,67,-6
1,19,64,1,2,0,8,59,1,1,2,...,2,1,0,4,0,0,1,0,61,2
2,24,98,2,2,1,7,91,2,1,2,...,2,1,1,4,0,2,2,1,74,-17
3,29,89,1,2,1,8,98,2,1,1,...,2,1,0,4,0,1,1,1,71,-27
4,19,92,2,2,1,6,65,2,1,3,...,0,1,1,4,0,0,2,0,70,5

In [147]:
#All Q5: Based on this dataset, what factors optimize attendance and scores?
#?
#school type performance comparison
#Bar chart of gender avgerage
#Pie chart of gender representaion in the 90 and greater grade range

#?
#Predictive Modeling
#Regression analysis: Build a regression model to predict final exam scores based on factors like study hours, attendance, parental involvement, and motivation.
#Machine learning: Use machine learning algorithms to identify students at risk of low performance.
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report


X = encoded_df.drop('Exam_Score', axis=1)  # Features
y = encoded_df['Exam_Score']  # Target variable
#Split the Data: Exam_Score the data into training and testing sets.
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

#Choose and Train a Machine Learning Model: Select a machine learning algorithm (e.g., Random Forest, Logistic Regression) and fit it to the training data.
model = RandomForestClassifier(random_state=42)
model.fit(X_train, y_train)

#Make Predictions: Use the model to predict the performance of students in the test set.
y_pred = model.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
print(f'Accuracy: {accuracy}')
print(classification_report(y_test, y_pred))

#Identify At-Risk Students: Based on the predictions, identify students who are predicted to be at risk of low performance.
at_risk_students = student_df.loc[y_pred == 'low_performance']
at_risk_students

Accuracy: 0.25705329153605017
              precision    recall  f1-score   support

          55       0.00      0.00      0.00         1
          58       0.00      0.00      0.00         4
          59       0.00      0.00      0.00         6
          60       0.00      0.00      0.00        18
          61       0.35      0.30      0.32        30
          62       0.22      0.22      0.22        45
          63       0.21      0.16      0.18        77
          64       0.28      0.27      0.28        96
          65       0.26      0.30      0.28       135
          66       0.23      0.28      0.26       141
          67       0.22      0.27      0.24       127
          68       0.28      0.39      0.32       143
          69       0.34      0.25      0.29       144
          70       0.26      0.31      0.28       108
          71       0.21      0.20      0.20        70
          72       0.25      0.23      0.24        56
          73       0.22      0.06      0.10        32
          74       0.25      0.09      0.13        23
          75       0.50      0.12      0.20         8
          76       0.00      0.00      0.00         2
          77       0.00      0.00      0.00         2
          83       0.00      0.00      0.00         1
          86       0.00      0.00      0.00         1
          94       0.00      0.00      0.00         2
          96       0.00      0.00      0.00         1
          98       0.00      0.00      0.00         1
          99       0.00      0.00      0.00         1
         100       0.00      0.00      0.00         1

    accuracy                           0.26      1276
   macro avg       0.15      0.12      0.13      1276
weighted avg       0.25      0.26      0.25      1276

/opt/anaconda3/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/opt/anaconda3/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/opt/anaconda3/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

KeyError: "None of [Index([70, 68, 64, 70, 67, 70, 71, 64, 66, 68,\n       ...\n       67, 63, 65, 68, 70, 68, 65, 66, 70, 68],\n      dtype='int64', length=1276)] are in the [columns]"

In [125]:

#plt.savefig("output_data/Fig7.png")
#plt.savefig("output_data/Fig8.png")

IndexError: Boolean index has wrong length: 1276 instead of 6377

In [ ]:
#Visualizations

#Scatter plots: Visualize the relationship between two continuous variables (e.g., study hours and final exam score).

#Box plots: Compare the distribution of final exam scores across different groups (e.g., gender, socioeconomic status).
#Private and public dataframes
#private_school_dataframe = student_df[(student_df["School_Type"] == "Private")]
#public_school_dataframe = student_df[(student_df["School_Type"] == "Public")]
#Histograms: Analyze the distribution of a single variable (e.g., final exam scores).

#Heatmaps: Visualize correlations between multiple variables.

In [ ]:
#Specific Example:
#Calculate the impact of tutoring on final exam scores:

#Group students: Divide students into two groups: those who attended tutoring sessions and those who didn't.
#Compare average scores: Calculate the average final exam score for each group.
#Perform a t-test: Conduct a t-test to determine if the difference in average scores is statistically significant

In [ ]:
linearRegressionplots(student_df["Exam_Score"], student_df["Attendance"], "Exam Score", "Attendance", "Exam Score by Attendance")
#linearRegressionplots(student_df["Attendance"], student_df["Exam_Score"], "Attendance", "Exam Score", "Attendance by Exam Score")

In [ ]:
linearRegressionplots(student_df["Exam_Score"], student_df["Teacher_Quality"], "Exam Score", "Teacher_Quality", "Exam Score by Teacher_Quality")
#linearRegressionplots(student_df["Teacher_Quality"], student_df["Exam_Score"], "Teacher_Quality", "Exam Score", "Teacher_Quality by Exam Score")

In [ ]:
linearRegressionplots(student_df["Exam_Score"], student_df["Parental_Involvement"], "Exam Score", "Parental_Involvement", "Exam Score by Parental_Involvement")
#linearRegressionplots(student_df["Parental_Involvement"], student_df["Exam_Score"], "Parental_Involvement", "Exam Score", "Parental_Involvement by Exam Score")

In [ ]:
linearRegressionplots(student_df["Exam_Score"], student_df["Motivation_Level"], "Exam Score", "Motivation_Level", "Exam Score by Motivation_Level")
#linearRegressionplots(student_df["Motivation_Level"], student_df["Exam_Score"], "Motivation_Level", "Exam Score", "Motivation_Level by Exam Score")

In [ ]:
linearRegressionplots(student_df["Exam_Score"], student_df["Hours_Studied"], "Exam Score", "Hours_Studied", "Exam Score by Hours_Studied")
#linearRegressionplots(student_df["Hours_Studied"], student_df["Exam_Score"], "Hours_Studied", "Exam Score", "Hours Studied by Exam Score")